# Calculating inverse matrix is costly process, here two functions are provided
# to cache and retrieve inverse matrix.

# Create a special version of a invertiable matrix that can cache its inverse.
# 
# Args:
# 	x: a invertiable matrix to be stored. Default to an empty matrix.
#	
# Returns:
# 	a list which contains a set of methods for get/set invertiable matrix
#	and get/set inverted version the matrix
#	
# Note:
#	If the original matrix is modified, its cached inverse matrix will be cleared	 
makeCacheMatrix <- function(x = matrix()) {
	matrixInverse <- NULL
	
	# modify original matrix
	set <- function(y) {
		x <<- y
		matrixInverse <<- NULL
	}
	
	# get original matrix
	get <- function() x
	
	# cache the inverse version of the original matrix
	setInverse <- function(inverse) matrixInverse <<- inverse
	
	# get the cached inverse matrix
	getInverse <- function() matrixInverse
	
	list(set = set, get = get, setInverse = setInverse, getInverse = getInverse)
}


# Calculate the inverse of a matrix and retrieve cached version if its already calculated
# 
# Args:
# 	x: a special version of the matrix generated by calling makeCacheMatrix
#	
# Returns:
# 	Inverse of the input matrix
#	
# Note:
#	This method assumes that the input matrix is always invertiable
cacheSolve <- function(x, ...) {
	# get cached version of the inverse matrix
	matrixInverse <- x$getInverse()
	
	# check whether it is already cached
	if (!is.null(matrixInverse)) {
		message("Retrieved cached data")
		return(matrixInverse)
	}        
	
	# get the original matrix
	matrixData <- x$get()
	
	# calculate inverse matrix
	matrixInverse <- solve(matrixData, ...)
	
	# cache inverse matrix result
	x$setInverse(matrixInverse)
	
	matrixInverse
}
